"""data_gen.py — Deep-Search Position Labeling for Nexus Chess NNUE (Gravity Rules).

Reads binary position files generated by ``self_play.py``, runs a deeper
Alpha-Beta search on each position using the gravity-lock rules engine,
and writes the labeled dataset to an HDF5 file.

Usage
-----
.. code-block:: bash

    python -m training.data_gen --input data/positions/ --output data/train_data.h5
"""

from __future__ import annotations

import argparse
import os
import struct
import sys
import time
from multiprocessing import Pool
from typing import List, Optional, Tuple

import h5py
import numpy as np

# Allow running as script.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from nnue.features import (
    BOARD_SIZE,
    compress_features,
    extract_features,
    feature_index,
    RAW_FEATURE_DIM,
)

from training.gravity_rules import (
    EMPTY,
    WHITE,
    BLACK,
    NUM_SQUARES,
    INITIAL_BOARD,
    alpha_beta as gravity_alpha_beta,
    evaluate_board,
    _apply_move,
    get_legal_moves,
    is_sanctuary_victory,
    is_siege_victory,
    _piece_color,
    _opponent,
)


# ═══════════════════════════════════════════════════════════════════════════════
# Position File I/O
# ═══════════════════════════════════════════════════════════════════════════════

def read_positions(
    filepath: str,
) -> List[Tuple[np.ndarray, int]]:
    """Read positions from a binary game file.

    Args:
        filepath: Path to a ``.bin`` game file.

    Returns:
        List of ``(board_array, side_to_move)`` tuples.
    """
    positions: List[Tuple[np.ndarray, int]] = []
    with open(filepath, "rb") as f:
        data = f.read()

    if len(data) < 4:
        return positions

    num_positions = struct.unpack("<I", data[:4])[0]
    offset = 4
    record_size = 49 + 4 + 4  # board (49) + score (4) + result (4)

    for i in range(num_positions):
        start = offset + i * record_size
        if start + record_size > len(data):
            break
        board_bytes = data[start : start + 49]
        board = np.frombuffer(board_bytes, dtype=np.uint8).copy()
        # Infer side: even position index = White to move.
        side = i % 2
        positions.append((board, side))

    return positions


def load_all_positions(input_dir: str) -> List[Tuple[np.ndarray, int]]:
    """Load all positions from all game files in a directory.

    Args:
        input_dir: Directory containing ``.bin`` game files.

    Returns:
        Combined list of all ``(board, side_to_move)`` tuples.
    """
    all_positions: List[Tuple[np.ndarray, int]] = []
    files = sorted(
        f for f in os.listdir(input_dir) if f.endswith(".bin")
    )

    print(f"Found {len(files)} game files in {input_dir}")

    for fname in files:
        path = os.path.join(input_dir, fname)
        positions = read_positions(path)
        all_positions.extend(positions)

    print(f"Loaded {len(all_positions)} total positions")
    return all_positions


# ═══════════════════════════════════════════════════════════════════════════════
# Deep Search Labeling (Gravity Rules)
# ═══════════════════════════════════════════════════════════════════════════════

def label_position(
    args: Tuple[np.ndarray, int, int]
) -> Tuple[List[int], float]:
    """Label a single position with a deep Alpha-Beta score.

    Uses the gravity-lock evaluation function at depth 0 for speed,
    or runs a deeper Alpha-Beta search depending on depth.

    Args:
        args: ``(board_array, side_to_move, search_depth)``.

    Returns:
        ``(raw_feature_indices, deep_search_score)``.
    """
    board, side, depth = args
    features = extract_features(board, side)
    # Deep-search labeling uses gravity rules Alpha-Beta.
    if depth > 0:
        score = gravity_alpha_beta(board, side, depth)
    else:
        score = evaluate_board(board, side)
    return features, score


def label_positions_parallel(
    positions: List[Tuple[np.ndarray, int]],
    depth: int = 10,
    num_workers: int = 8,
) -> Tuple[List[List[int]], List[float]]:
    """Label all positions in parallel.

    Args:
        positions:   List of ``(board, side)`` tuples.
        depth:       Alpha-Beta search depth.
        num_workers: Number of parallel workers.

    Returns:
        ``(all_features, all_scores)`` where features are lists of raw indices.
    """
    work_items = [(board, side, depth) for board, side in positions]

    print(f"Labeling {len(work_items)} positions at depth {depth} "
          f"with {num_workers} workers...")
    t0 = time.time()

    with Pool(processes=num_workers) as pool:
        results = pool.map(label_position, work_items)

    elapsed = time.time() - t0
    print(f"Labeling complete in {elapsed:.1f}s "
          f"({len(results) / max(elapsed, 0.001):.1f} pos/sec)")

    all_features = [r[0] for r in results]
    all_scores = [r[1] for r in results]

    return all_features, all_scores


# ═══════════════════════════════════════════════════════════════════════════════
# HDF5 Output
# ═══════════════════════════════════════════════════════════════════════════════

def build_feature_map_from_data(
    all_features: List[List[int]],
    target_dim: int = 20480,
) -> dict:
    """Build compressed feature map from collected feature lists.

    Args:
        all_features: List of raw feature index lists.
        target_dim:   Target compressed dimension.

    Returns:
        Dict mapping ``raw_index → compressed_index``.
    """
    from collections import Counter

    counter: Counter = Counter()
    for feats in all_features:
        counter.update(feats)

    most_common = counter.most_common(target_dim)
    feature_map: dict = {}
    for compressed_idx, (raw_idx, _) in enumerate(most_common):
        feature_map[raw_idx] = compressed_idx

    print(f"Built feature map: {len(feature_map)} features "
          f"(out of {len(counter)} unique raw features)")
    return feature_map


def write_hdf5(
    output_path: str,
    all_features: List[List[int]],
    all_scores: List[float],
    feature_map: dict,
    input_dim: int = 20480,
    train_split: float = 0.9,
) -> None:
    """Write compressed feature vectors and scores to an HDF5 file.

    Args:
        output_path:  Destination HDF5 path.
        all_features: Raw feature lists per position.
        all_scores:   Target scores per position.
        feature_map:  Raw → compressed index mapping.
        input_dim:    Compressed input dimension.
        train_split:  Fraction of data for training (rest for validation).
    """
    n = len(all_features)
    indices = np.random.RandomState(42).permutation(n)
    split_idx = int(n * train_split)

    train_indices = indices[:split_idx]
    val_indices = indices[split_idx:]

    print(f"Compressing features to dim={input_dim}...")
    t0 = time.time()

    def _compress_batch(idxs: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
        feats = np.zeros((len(idxs), input_dim), dtype=np.float32)
        scores = np.zeros((len(idxs), 1), dtype=np.float32)
        for i, idx in enumerate(idxs):
            compressed = compress_features(all_features[idx], feature_map, input_dim)
            feats[i] = compressed
            scores[i, 0] = all_scores[idx]
        return feats, scores

    train_feats, train_scores = _compress_batch(train_indices)
    val_feats, val_scores = _compress_batch(val_indices)

    elapsed = time.time() - t0
    print(f"Compression complete in {elapsed:.1f}s")

    with h5py.File(output_path, "w") as f:
        f.create_dataset("train/features", data=train_feats, compression="gzip")
        f.create_dataset("train/scores", data=train_scores, compression="gzip")
        f.create_dataset("val/features", data=val_feats, compression="gzip")
        f.create_dataset("val/scores", data=val_scores, compression="gzip")
        f.attrs["input_dim"] = input_dim
        f.attrs["num_train"] = len(train_indices)
        f.attrs["num_val"] = len(val_indices)

    map_path = output_path.replace(".h5", "_feature_map.npy")
    np.save(map_path, feature_map)

    print(f"Written {len(train_indices)} train + {len(val_indices)} val "
          f"samples to {output_path}")
    print(f"Feature map saved to {map_path}")


# ═══════════════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════════════

def main() -> None:
    """Data generation and labeling entry point."""
    parser = argparse.ArgumentParser(
        description="Nexus Chess Deep-Search Data Labeling (Gravity Rules)"
    )
    parser.add_argument(
        "--input", type=str, default="data/positions/",
        help="Input directory with .bin position files."
    )
    parser.add_argument(
        "--output", type=str, default="data/train_data.h5",
        help="Output HDF5 file path."
    )
    parser.add_argument(
        "--depth", type=int, default=6,
        help="Alpha-Beta search depth for labeling (default: 6, equivalent to 10 with TT)."
    )
    parser.add_argument(
        "--workers", type=int, default=8,
        help="Number of parallel workers (default: 8)."
    )
    parser.add_argument(
        "--input-dim", type=int, default=20480,
        help="Compressed feature input dimension (default: 20480)."
    )
    parser.add_argument(
        "--train-split", type=float, default=0.9,
        help="Fraction of data for training (default: 0.9)."
    )
    args = parser.parse_args()

    # 1. Load positions.
    positions = load_all_positions(args.input)
    if not positions:
        print("ERROR: No positions found. Run self_play.py first.")
        sys.exit(1)

    # 2. Deep-search labeling.
    all_features, all_scores = label_positions_parallel(
        positions, depth=args.depth, num_workers=args.workers
    )

    # 3. Build feature map.
    feature_map = build_feature_map_from_data(all_features, args.input_dim)

    # 4. Write HDF5.
    write_hdf5(
        args.output,
        all_features,
        all_scores,
        feature_map,
        input_dim=args.input_dim,
        train_split=args.train_split,
    )

    print("\n=== Data Generation Complete ===")


if __name__ == "__main__":
    main()
